const actions = {
    
    ADD_NUM_TO_CALC: "ADD_NUM_TO_CALC",
    ADD_OPERATOR_TO_CALC: "ADD_OPERATOR_TO_CALC",
    CALCULATE_RESULT: "CALCULATE_RESULT",
    CLEAR_LAST_INPUT: "CLEAR_LAST_INPUT",
    CLEAR_CURRENT_CALCULATION: "CLEAR_CURRENT_CALCULATION"
    
}