export default {

    SET_NUM: "SET_NUM",
    CLEAR_NUM: "CLEAR_NUM",
    SET_CURRENT_CALC_OP: "SET_CURRENT_CALC_OP",
    SET_PREV_NUM: "SET_PREV_NUM",
    SET_DOT_IN_NUM: "SET_DOT_IN_NUM",
    SET_SYMBOL_ON_DISPLAY: "SET_SYMBOL_ON_DISPLAY",
    ADD_TO_CURRENT_HISTORY: "ADD_TO_CURRENT_HISTORY",
    REMOVE_LAST_FROM_CURRENT_HISTORY: "REMOVE_LAST_FROM_CURRENT_HISTORY",
    REMOVE_ALL_FROM_CURRENT_HISTORY: "REMOVE_ALL_FROM_CURRENT_HISTORY",
    ADD_TO_COMPLETE_HISTORY: "ADD_TO_COMPLETE_HISTORY",
    CALCULATE_RESULT: "CALCULATE_RESULT",
    CLEAR_CURRENT_CALCULATION: "CLEAR_CURRENT_CALCULATION"

}