export default {

    ADD_NUM_TO_CALC: "ADD_NUM_TO_CALC",
    ADD_OPERATOR_TO_CALC: "ADD_OPERATOR_TO_CALC",
    CALC_PREVIOUS_RESULT: "CALC_PREVIOUS_RESULT",
    SET_NEXT_INPUT_TYPE_TO_NUM: "SET_NEXT_INPUT_TYPE",
    ADD_TO_CURRENT_HISTORY: "ADD_TO_CURRENT_HISTORY",
    REMOVE_LAST_FROM_CURRENT_HISTORY: "REMOVE_LAST_FROM_CURRENT_HISTORY",
    REMOVE_ALL_FROM_CURRENT_HISTORY: "REMOVE_ALL_FROM_CURRENT_HISTORY",
    ADD_TO_COMPLETE_HISTORY: "ADD_TO_COMPLETE_HISTORY",
    CALCULATE_RESULT: "CALCULATE_RESULT",
    CLEAR_LAST_INPUT: "CLEAR_LAST_INPUT",
    CLEAR_CURRENT_CALCULATION: "CLEAR_CURRENT_CALCULATION"

}